# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('logotype', models.ImageField(blank=True, upload_to='templates/images/logo/')),
                ('business_name', models.CharField(max_length=70)),
                ('commercial_business', models.CharField(blank=True, max_length=150)),
                ('rut', models.CharField(max_length=9, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
