# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='mail',
        ),
    ]
