# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 20:59
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_remove_enterprise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
